# Generated by Django 3.2.12 on 2023-07-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerService',
            new_name='Ticket',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'ticket'},
        ),
    ]
