# Generated by Django 4.2.3 on 2023-07-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
    ]
