# Generated by Django 4.2.3 on 2023-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
