# Generated by Django 4.2.1 on 2023-06-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='cart',
        ),
    ]
