# Generated by Django 3.2.12 on 2023-07-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name_plural': 'login'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'signup'},
        ),
    ]
