# Generated by Django 4.2.1 on 2023-06-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
