# Generated by Django 4.2.3 on 2023-08-30 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('refund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refund.refund')),
            ],
        ),
    ]
