# Generated by Django 4.2.3 on 2023-07-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0002_remove_refund_cart'),
        ('cart', '0002_cart_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='refund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='refund.refund'),
        ),
    ]
