# Generated by Django 4.2.3 on 2023-07-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('order', '0002_order_cart_order_customer_order_deliver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=244, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.cart'),
            preserve_default=False,
        ),
    ]
